apiVersion: v1
kind: Service

metadata:
  name: react-vite-service
  namespace: frontend

spec:
  type: NodePort

  selector:
    app: react-vite

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081

