apiVersion: v1
kind: Service
metadata:
  name: grishma-portfolio-service
  namespace: portfolio
spec:
  selector:
    app: grishma-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort